/**
 * Legal copy for the Terms & Conditions and Privacy Policy pages.
 *
 * Kept as data so the same text can be reused by the mobile app's in-app
 * screens and by the acceptance gate on the login form.
 *
 * NOT LEGAL ADVICE — reviewed wording is the operator's responsibility.
 */

export const LEGAL_EFFECTIVE = '1 July 2026';
export const LEGAL_OPERATOR = 'Tushar Dube';
export const LEGAL_ENTITY = 'SolidCoreATS';

/**
 * Terms. The five clauses supplied separately are merged in rather than
 * appended: the medical disclaimer absorbs the old "Health & Fitness
 * Disclaimer", and the liability cap absorbs the old "Limitation of
 * Liability", so nothing is stated twice or contradicted.
 */
export const TERMS = [
  {
    title: 'Acceptance of Terms',
    body: [
      `By downloading, accessing, or using the SolidCore application ("the App") you agree to be bound by these Terms & Conditions. If you do not agree, please discontinue use of the App.`,
      `You are asked to accept these Terms and the Privacy Policy once, at sign-in. Sign-in cannot be completed without that acceptance, and the date and version you accepted are recorded against your account.`,
    ],
  },
  {
    title: 'Use of the App',
    body: [
      `SolidCore is provided for general fitness, training, and informational purposes. You agree to use the App only for lawful purposes and not to misuse, reverse-engineer, or interfere with its normal operation.`,
    ],
  },
  {
    title: 'Important Medical Disclaimer',
    highlight: true,
    body: [
      `No medical advice. The services, text, data, graphics, charts, workload calculations, and metrics generated by this platform — including but not limited to acute-to-chronic workload ratios, wellness scores, body composition estimates, and fatigue tracking — are for informational and sports performance tracking purposes only.`,
      `This platform does not provide medical advice, diagnosis, or treatment. The contents of this App are not intended to be a substitute for professional medical advice, diagnosis, or rehabilitation. Always seek the advice of your physician, physiotherapist, or other qualified healthcare provider with any questions you may have regarding a medical condition or physical injury.`,
      `Never disregard professional medical advice, or delay seeking it, because of something you have read or interpreted on this platform.`,
    ],
  },
  {
    title: 'No Doctor–Patient Relationship',
    body: [
      `Your use of this software — including the submission of personal wellness data, training logs, or communication with any customer support — does not create a clinician-patient, doctor-patient, or therapist-patient relationship between you and the platform owner.`,
      `The platform owner acts strictly as a technology provider, not as your personal healthcare provider.`,
    ],
  },
  {
    title: 'Assumption of Risk & Fitness to Participate',
    body: [
      `You explicitly acknowledge that athletic training and sports performance tracking carry inherent risks of severe physical injury or illness.`,
      `By using this platform, you certify that you are physically fit to participate in the training programmes logged herein. You assume all risks associated with your training, and agree that the platform is merely a recording and analytical tool — not a monitoring system for medical safety.`,
    ],
  },
  {
    title: 'Explicit Consent to Tracking',
    highlight: true,
    body: [
      `Tracking of your physical metrics, sleep, and fatigue requires your explicit consent. You must tick an "I agree" box before any such data is collected — consent is never assumed, pre-ticked, or bundled with other permissions.`,
      `Consent is granular and reversible. You can review or withdraw it at any time in Privacy & Security; withdrawing consent disables the related feature going forward.`,
    ],
  },
  {
    title: 'Accounts',
    body: [
      `You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.`,
    ],
  },
  {
    title: '"As-Is" Data & No Guarantee',
    body: [
      `The platform and its analytics are provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, that the software will accurately predict or prevent injuries, overtraining, or performance drops.`,
      `Human bodies react dynamically, and the software's outputs are strictly mathematical interpretations of data provided entirely by the user.`,
    ],
  },
  {
    title: 'Intellectual Property',
    body: [
      `All content, trademarks, and software in the App are owned by or licensed to ${LEGAL_ENTITY} and may not be copied or redistributed without permission.`,
    ],
  },
  {
    title: 'Limitation of Liability',
    highlight: true,
    body: [
      `To the maximum extent permitted by applicable law, in no event shall the platform, its founders, or affiliates be liable for any direct, indirect, punitive, incidental, special, or consequential damages — including but not limited to personal injury, wrongful death, loss of athletic performance, or data loss — arising from your use of the App.`,
      `In any event, the total aggregate liability of the platform for any claims arising out of these Terms shall be limited to the total amount actually paid by you to the platform in the three (3) months preceding the claim.`,
    ],
  },
  {
    title: 'Changes to These Terms',
    body: [
      `We may update these Terms from time to time. Continued use of the App after changes take effect constitutes acceptance of the revised Terms.`,
    ],
  },
  {
    title: 'Contact',
    body: [`Questions about these Terms can be sent to support@solidcoreats.com.`],
  },
];

export const PRIVACY = [
  {
    title: 'Overview',
    body: [
      `This Privacy Policy explains how ${LEGAL_ENTITY} (operated by ${LEGAL_OPERATOR}) collects, uses, and protects your information when you use the App.`,
    ],
  },
  {
    title: 'Information We Collect',
    body: [
      `We collect the information you provide directly — such as your profile details and the measurements you enter — as well as the training, recovery, and body-composition data generated as you use the App.`,
    ],
  },
  {
    title: 'On-Device Processing',
    body: [
      `Wherever possible, analyses such as body composition and camera-based movement assessments are processed on your device. Data stored on your device stays under your control.`,
    ],
  },
  {
    title: 'How We Use Your Information',
    body: [
      `Your information is used to calculate your scores, personalise insights, and improve the App. We do not sell your personal data.`,
    ],
  },
  {
    title: 'Consent',
    body: [
      `Tracking of physical metrics, sleep, and fatigue requires your explicit opt-in. You must tick an "I agree" box before any such data is collected — nothing is pre-ticked and consent is never assumed.`,
      `You can control data-collecting features through the consent settings in Privacy & Security. Withdrawing consent disables the related feature going forward.`,
    ],
  },
  {
    title: 'Data Retention & Deletion',
    body: [
      `You may delete your logs and account data at any time from within the App. Deleted data is removed from your device.`,
    ],
  },
  {
    title: 'Security',
    body: [
      `We use reasonable technical and organisational measures to protect your information, though no method of storage or transmission is completely secure.`,
    ],
  },
  {
    title: 'Contact',
    body: [`For privacy questions or requests, contact support@solidcoreats.com.`],
  },
];
